### ISSUE TITLE
A more complete abstract? 

### ISSUE THREAD

**Issue by ZiluTian** [OrganicIrradiation/scholarly#14] opened 2018-02-24 13:37 UTC
Hello, 
Thanks for this awesome piece of work! I am wondering if there is any suggestion for how to retrieve the entire abstract? RIght now I see a lot of broken sentences. Assume that I have proper certificate to retrieve the document following the url. Thanks!

**Comment by OrganicIrradiation** [comment] 2019-02-13 23:41
I'm not sure of a way to get the full abstract without adding additional queries (which will make you hit the Scholar query limit quickly).

**Comment by OrganicIrradiation** [comment] 2019-06-06 15:48
Without a suggested solution, I'm going to close this issue because it's an inherent limitation of querying Google Scholar.

**Closed by OrganicIrradiation** 2019-06-06 15:48 UTC

**Comment by MartinBeseda** [comment] 2019-06-19 14:05
@OrganicIrradiation 
More complete version of the abstract extracted directly from the search page could be obtained in this way:

```
from lxml import html
import requests
page = requests.get('https://scholar.google.com/scholar?hl=cs&as_sdt=0%2C5&q=The+Spectra+and+Dynamics+of+Diatomic+Molecules%3A+Revised+and+Enlarged+Edition&btnG=')
tree = html.fromstring(page.content)
abstract=''.join(tree.xpath('//div[@class="gs_rs"]/text()'))

>>> abstract
'This book is written for graduate students just beginning research, for theorists curious about what experimentalists actually can and do measure, and for experimentalists bewildered by theory. It is a guide for potential users of spectroscopic data, and uses language and concepts that bridge the frequency-and time-domain spectroscopic communities. Key topics, concepts, and techniques include: the assignment of simple spectra, basic experimental techniques, definition of Born-Oppenheimer and angular momentum basis sets and the\xa0…'
```

**Comment by OrganicIrradiation** [comment] 2019-06-19 14:18
@MartinBeseda: That's the same abstract returned by scholarly:

```python
>>> import scholarly
>>> query = scholarly.search_pubs_query('The Spectra and Dynamics of Diatomic Molecules Revised')
>>> print(next(query))
{'_filled': False,
 'bib': {'abstract': 'This book is written for graduate students just '
                     'beginning research, for theorists curious about what '
                     'experimentalists actually can and do measure, and for '
                     'experimentalists bewildered by theory. It is a guide for '
                     'potential users of spectroscopic data, and uses language '
                     'and concepts that bridge the frequency-and time-domain '
                     'spectroscopic communities. Key topics, concepts, and '
                     'techniques include: the assignment of simple spectra, '
                     'basic experimental techniques, definition of '
                     'Born-Oppenheimer and angular momentum basis sets and the '
                     '…',
         'author': 'H Lefebvre-Brion and RW Field',
         'title': 'The Spectra and Dynamics of Diatomic Molecules: Revised and '
                  'Enlarged Edition',
         'url': 'https://books.google.com/books?hl=en&lr=&id=LwgHIo-NEccC&oi=fnd&pg=PP1&dq=The+Spectra+and+Dynamics+of+Diatomic+Molecules+Revised&ots=Hm8hxlypsp&sig=mcKZBS3yaeKuMMDqwUbOk0B2Acw'},
 'citedby': 744,
 'id_scholarcitedby': '6983983601199802940',
 'source': 'scholar',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:POqqIhUY7GAJ:scholar.google.com/&output=citation&scisdr=CgUGym3sGAA:AAGBfm0AAAAAXQpF7H8OEslAcsL0ps69MKuRrcRwx8Wh&scisig=AAGBfm0AAAAAXQpF7NPWPanGA3S0gZtEsnh_QZGRmdsm&scisf=4&ct=citation&cd=0&hl=en'}
```

**Comment by MartinBeseda** [comment] 2019-06-19 15:39
@OrganicIrradiation Strange... With  GS I'm getting the following abstract

```
This book is written for graduate students just beginning research, for theorists curious about what experimentalists actually can and do measure, and for experimentalists bewildered by theory. It is a guide for potential users of spectroscopic data, and uses language and …
```

**Comment by OrganicIrradiation** [comment] 2019-06-21 14:29
@MartinBeseda Can you provide a code snippet that reproduces the shorter abstract? Can you also confirm that searching on scholar.google.com with a desktop bowser on your computer pulls the longer abstract?

**Comment by MartinBeseda** [comment] 2019-06-21 14:54
@OrganicIrradiation Here we go...

**Scholarly API**
```
>>> import scholarly
>>> query = scholarly.search_pubs_query('https://aip.scitation.org/doi/abs/10.1063/1.466548')>>> paper=next(query).fill()
>>> print(paper.bib['abstract'])
The potential energy surfaces (PESs) of the three lowest electronic states of the system N+ 2+ He have been computed using accurate multiconfiguration‐reference configuration (MRCI) wave functions and a large basis set. The approach of the He atom leads to …
```

**HTML Scraping from scholar.google.com**
```
>>> from lxml import html
>>> import requests
>>> page = requests.get('https://scholar.google.cz/scholar?hl=cs&as_sdt=0%2C5&q=Quantum+scattering+studies+of+electronically+inelastic+collisions+of++N2%2B&btnG=')
>>> tree = html.fromstring(page.content)
>>> abstract=''.join(tree.xpath('//div[@class="gs_rs"]/text()'))
>>> abstract
"The potential energy surfaces (PESs) of the three lowest electronic states of the system N+ 2+ He have been computed using accurate multiconfiguration‐reference configuration (MRCI) wave functions and a large basis set. The approach of the He atom leads to nonadiabatic mixing of the A 2Πu (A') and X 2Σ+ g (A') states of N+ 2. The three adiabatic interaction potentials have been transformed into a set of four diabatic potentials, one of which describes the collision‐induced nonadiabatic coupling between the two A'states. The\xa0…"

```

**Comment by OrganicIrradiation** [comment] 2019-06-21 15:08
Those are two different queries. The returned abstracts are identical for the two methods if you use the same query. Here's the appropriate HTML comparisons:

```python
>>> import scholarly
>>> query = scholarly.search_pubs_query('https://aip.scitation.org/doi/abs/10.1063/1.466548')
>>> paper = next(query).fill()
>>> print(paper.bib['abstract'])
The potential energy surfaces (PESs) of the three lowest electronic states of the system N+ 2+ He have been computed using accurate multiconfiguration‐reference configuration (MRCI) wave functions and a large basis set. The approach of the He atom leads to …

>>> from lxml import html
>>> import requests
>>> page = requests.get('https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=https%3A%2F%2Faip.scitation.org%2Fdoi%2Fabs%2F10.1063%2F1.466548&btnG=')
>>> tree = html.fromstring(page.content)
>>> abstract = ''.join(tree.xpath('//div[@class="gs_rs"]/text()'))
>>> print(abstract)
The potential energy surfaces (PESs) of the three lowest electronic states of the system N+ 2+ He have been computed using accurate multiconfiguration‐reference configuration (MRCI) wave functions and a large basis set. The approach of the He atom leads to …
```

```python
>>> import scholarly
>>> query = scholarly.search_pubs_query('Quantum scattering studies of electronically inelastic collisions of  N2+')
>>> paper = next(query).fill()
>>> print(paper.bib['abstract'])
The potential energy surfaces (PESs) of the three lowest electronic states of the system N+ 2+ He have been computed using accurate multiconfiguration‐reference configuration (MRCI) wave functions and a large basis set. The approach of the He atom leads to nonadiabatic mixing of the A 2Πu (A') and X 2Σ+ g (A') states of N+ 2. The three adiabatic interaction potentials have been transformed into a set of four diabatic potentials, one of which describes the collision‐induced nonadiabatic coupling between the two A'states. The …

>>> from lxml import html
>>> import requests
>>> page = requests.get('https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=Quantum+scattering+studies+of+electronically+inelastic+collisions+of++N2%2B&btnG=')
>>> tree = html.fromstring(page.content)
>>> abstract = ''.join(tree.xpath('//div[@class="gs_rs"]/text()'))
>>> print(abstract)
The potential energy surfaces (PESs) of the three lowest electronic states of the system N+ 2+ He have been computed using accurate multiconfiguration‐reference configuration (MRCI) wave functions and a large basis set. The approach of the He atom leads to nonadiabatic mixing of the A 2Πu (A') and X 2Σ+ g (A') states of N+ 2. The three adiabatic interaction potentials have been transformed into a set of four diabatic potentials, one of which describes the collision‐induced nonadiabatic coupling between the two A'states. The …
```
