### ISSUE TITLE
v0.2.5 cannot use next for scholarly.search_pubs_query

### ISSUE THREAD

**Issue by YupingBai** [OrganicIrradiation/scholarly#41] opened 2019-06-06 19:48 UTC
i just update to v0.2.5, but after using scholarly.search_pubs_query
I cannot use next(scholarly.search_pubs_query(title)) to get the information

**Comment by YupingBai** [comment] 2019-06-06 19:49
report  StopIteration

**Comment by OrganicIrradiation** [comment] 2019-06-06 21:34
Do any other functions work? If not, you may have been rate-limited. If other commands work, could you provide an example snippet of code for me to try locally?

**Comment by YupingBai** [comment] 2019-06-07 06:03
scholarly.search_author can be used. but i find if has the time.sleep setup. if I cannot search many publications at the same time (or use iteration method), why do I need it to search it automatically? 
Thank you very much

**Comment by YupingBai** [comment] 2019-06-07 06:06
for example, the code like this,  the "tmp_paper_title"  can be any paper

tmp_paper_title = "Structural analysis of material flows in China based on physical and monetary input-output models"  
tmp_search = scholarly.search_pubs_query(tmp_paper_title)
tmp_bib_fill = next(tmp_search).fill()

**Comment by YupingBai** [comment] 2019-06-07 09:29
when I execute "tmp_bib_fill = next(tmp_search).fill()"  , it will report "StopIteration"

**Comment by OrganicIrradiation** [comment] 2019-06-07 16:18
I'm not having an issue, so I'm assuming that you've been rate-limited by Google:
``` python
>>> import pprint
>>> import scholarly
>>> tmp_paper_title = "Structural analysis of material flows in China based on physical and monetary input-output models"
>>> tmp_search = scholarly.search_pubs_query(tmp_paper_title)
>>> tmp_bib_fill = next(tmp_search).fill()
>>> pprint.pprint(tmp_bib_fill.__dict__)
{'_filled': True,
 'bib': {'ENTRYTYPE': 'article',
         'ID': 'liang2017structural',
         'abstract': 'The physical input-output (PIO) model has different '
                     'product flow scopes from the monetary input-output (MIO) '
                     'model. Using the PIO and MIO models to analyze the '
                     'structure of material flows can identify new hotspots '
                     'for policy decisions over each other. However, PIO '
                     'models are not well-studied in existing studies on the '
                     "structure of China's material flows. This study uses "
                     'both the PIO and MIO models to analyze consumption-based '
                     'material flows of Chinese sectors and critical supply '
                     "chain paths leading to China's material flows. Results "
                     'show that …',
         'author': 'Liang, Sai and Wang, Yafei and Zhang, Tianzhu and Yang, '
                   'Zhifeng',
         'eprint': '/scholar?output=instlink&q=info:XOhzwuduzXsJ:scholar.google.com/&hl=en&as_sdt=0,5&scillfp=2846449214753793698&oi=lle',
         'journal': 'Journal of Cleaner Production',
         'pages': '209--217',
         'publisher': 'Elsevier',
         'title': 'Structural analysis of material flows in China based on '
                  'physical and monetary input-output models',
         'url': 'https://www.sciencedirect.com/science/article/pii/S0959652617309174',
         'volume': '158',
         'year': '2017'},
 'citedby': 12,
 'id_scholarcitedby': '8920908378569697372',
 'source': 'scholar',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:XOhzwuduzXsJ:scholar.google.com/&output=citation&scisdr=CgUom4nJGAA:AAGBfm0AAAAAXPqQM46Wk5WFkXaXPmRxZejm3v0BeQQ3&scisig=AAGBfm0AAAAAXPqQM-zZGBdKFu8gpbqRF75eKZlS9GY9&scisf=4&ct=citation&cd=0&hl=en'}
```

**Comment by YupingBai** [comment] 2019-06-07 16:42
Thanks for your reply. If I have hundreds of papers need to be searched, could I banned by the google? If so. how can I solve it? or how can I search hundreds of papers using loops?

can it solve the problem replacing scholarly.scholarly._HEADERS["User-Agent"] 


Your client does not have permission to get URL /scholar.enw?q=info:40eUk9hfkSgJ:scholar.google.com/&output=citation&scisdr=CgUFm6SAENGEvB2TGHg:AAGBfm0AAAAAXPqWAHhfTz6ZSbnWCjmvJ-WOs7WkfYHI&scisig=AAGBfm0AAAAAXPqWALp61s9AvPAClcPJNtbtmOCJBoG0&scisf=3&ct=citation&cd=0&hl=zh-CN from this server.





import glob
import scholarly
from bibtexparser.bwriter import BibTexWriter
from bibtexparser.bibdatabase import BibDatabase
import gc
import time
from fake_useragent import UserAgent


pdf_file_path = 'P:\\research content\\MRIO_land_intensity\\biodiversity\\'
pdf_file_list = glob.glob(pdf_file_path + "*.pdf")
bib_path = 'E:\\download_bib\\'

for i in range(len(pdf_file_list)):
    ua = UserAgent()
    scholarly.scholarly._HEADERS["User-Agent"] = ua.chrome
    tmp_pdf_name = pdf_file_list[i].split("\\")[-1]
    tmp_paper_title = tmp_pdf_name[:-4]
    tmp_search = scholarly.scholarly.search_pubs_query(tmp_paper_title)
    tmp_bib_fill = next(tmp_search).fill()
    tmp_bib = tmp_bib_fill.bib
    try:
        db = BibDatabase()
        db.entries = [tmp_bib]
        writer = BibTexWriter()
        tmp_bib_writer_name = tmp_paper_title + '.bib'
        tmp_bib_writer_file = bib_path + tmp_bib_writer_name
        with open(tmp_bib_writer_file, 'w') as bibfile:
            bibfile.write(writer.write(db))
    except:
        print(tmp_bib_writer_name + "  error")
        continue
    else:
         print(tmp_bib_writer_name + "  successfully")
    del db, writer
    ua.update()
    time.sleep(5)
    gc.collect()

**Comment by YupingBai** [comment] 2019-06-07 16:47
Thanks for your reply. If I have hundreds of papers need to be searched, could it possible to be banned by the google? If so. how can I solve it? or how can I search hundreds of papers using loops?

can it solve the problem replacing scholarly.scholarly._HEADERS["User-Agent"]

error 403
Your client does not have permission to get URL /scholar.enw?q=info:40eUk9hfkSgJ:scholar.google.com/&output=citation&scisdr=CgUFm6SAENGEvB2TGHg:AAGBfm0AAAAAXPqWAHhfTz6ZSbnWCjmvJ-WOs7WkfYHI&scisig=AAGBfm0AAAAAXPqWALp61s9AvPAClcPJNtbtmOCJBoG0&scisf=3&ct=citation&cd=0&hl=zh-CN from this server.

```
> import glob
> import scholarly
> from bibtexparser.bwriter import BibTexWriter
> from bibtexparser.bibdatabase import BibDatabase
> import gc
> import time
> from fake_useragent import UserAgent
> 
> 
> pdf_file_path = 'P:\\research content\\MRIO_land_intensity\\biodiversity\\'
> pdf_file_list = glob.glob(pdf_file_path + "*.pdf")
> bib_path = 'E:\\download_bib\\'
> 
> for i in range(len(pdf_file_list)):
>     ua = UserAgent()
>     scholarly.scholarly._HEADERS["User-Agent"] = ua.chrome
>     tmp_pdf_name = pdf_file_list[i].split("\\")[-1]
>     tmp_paper_title = tmp_pdf_name[:-4]
>     tmp_search = scholarly.scholarly.search_pubs_query(tmp_paper_title)
>     tmp_bib_fill = next(tmp_search).fill()
>     tmp_bib = tmp_bib_fill.bib
>     try:
>         db = BibDatabase()
>         db.entries = [tmp_bib]
>         writer = BibTexWriter()
>         tmp_bib_writer_name = tmp_paper_title + '.bib'
>         tmp_bib_writer_file = bib_path + tmp_bib_writer_name
>         with open(tmp_bib_writer_file, 'w') as bibfile:
>             bibfile.write(writer.write(db))
>     except:
>         print(tmp_bib_writer_name + "  error")
>         continue
>     else:
>          print(tmp_bib_writer_name + "  successfully")
>     del db, writer
>     ua.update()
>     time.sleep(5)
>     gc.collect()
```

**Comment by OrganicIrradiation** [comment] 2019-06-07 16:49
> Thanks for your reply. If I have hundreds of papers need to be searched, could I banned by the google? If so. how can I solve it? or how can I search hundreds of papers using loops?

Yes, you can and will be temporarily banned if the user agent cannot solve a CAPTCHA. This will happen regardless of the User-Agent because it is tied to your IP address. You should be able to reconnect after a few hours. Unfortunately, there is no way to bypass or solve the CAPTCHA in the current version, but you are welcome to try to find a solution!

**Comment by ipeirotis** [comment] 2019-06-07 16:52
One solution is to use a proxy (see the `use_proxy` command added in https://github.com/OrganicIrradiation/scholarly/pull/26) and potentially proxy through Tor.

**Comment by YupingBai** [comment] 2019-06-07 17:09
> One solution is to use a proxy (see the `use_proxy` command added in #26) and potentially proxy through Tor.

Thanks for your suggestion. I just uninstall scholarly, and then install scholarly. But I did not find `scholarly. user_proxy()` function
in addition, if it has the function, how can I send a new proxy for each loop?

thanks

**Comment by ipeirotis** [comment] 2019-06-07 17:12
Tor will take care of sending the request through a different IP each time. I am not sure if the latest version of scholarly on PyPI has the `has_proxy` into the build. (@OrganicIrradiation may need to initiate an additional build)

**Comment by YupingBai** [comment] 2019-06-07 17:18
> Tor will take care of sending the request through a different IP each time. I am not sure if the latest version of scholarly on PyPI has the `has_proxy` into the build. (@OrganicIrradiation may need to initiate an additional build)

oh, no, the same computer and the same network, I cannot create different IP. Do you have an idea how to use different IP. Because I have hundreds of papers. 
thanks

**Comment by OrganicIrradiation** [comment] 2019-06-07 17:18
The latest PyPi version does not currently have that feature; however you can install the latest github version in the meantime with ```pip install git+https://github.com/OrganicIrradiation/scholarly.git```

**Comment by ipeirotis** [comment] 2019-06-21 18:28
@YupingBai 

If you want to use the latest version with Tor:

* `pip install -U git+https://github.com/OrganicIrradiation/scholarly.git`
* `pip install -U PySocks`

Then install Tor. In a Debian-based Linux system, just run:

`sudo apt-get install tor`

The tor process starts automatically and listens on port 9050.

To verify that the tor process is running, run:

`ps aux | grep '\btor\b'`

To verify the port where tor is listening, run:

`sudo netstat -l -n -p | grep tor`

Then you can use scholarly as follows:

```
    import scholarly

    proxies = {'http' : 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
    scholarly.scholarly.use_proxy(**proxies)

    print(next(scholarly.search_author('Steven A. Cholewiak')))
```

**Comment by jmlgh** [comment] 2019-07-02 15:57
@ipeirotis 
I'm getting this exception using proxies:
`requests.exceptions.ProxyError: HTTPSConnectionPool(host='scholar.google.com', port=443): Max retries exceeded with url: /scholar?q=miguel+holgado+bola%C3%B1os&as_ylo=2018 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 501 Tor is not an HTTP Proxy',)))`
Any idea what could be causing this?

**Comment by ipeirotis** [comment] 2019-07-02 16:03
> @ipeirotis
> I'm getting this exception using proxies:
> `requests.exceptions.ProxyError: HTTPSConnectionPool(host='scholar.google.com', port=443): Max retries exceeded with url: /scholar?q=miguel+holgado+bola%C3%B1os&as_ylo=2018 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 501 Tor is not an HTTP Proxy',)))`
> Any idea what could be causing this?

Hard to tell without looking at your code.

**Comment by jmlgh** [comment] 2019-07-03 11:21
I've been looking into this issue. As @YupingBai has mentioned, `search_author` works fine but not `search_pubs_query`. The problem seems to be that the 'gs_or' div class is not being found here:
```
def _search_scholar_soup(soup):
    """Generator that returns Publication objects from the search page"""
    while True:
        for row in soup.find_all('div', class_='gs_or'):
            yield Publication(row, 'scholar')
        if soup.find(class_='gs_ico gs_ico_nav_next'):
            url = soup.find(class_='gs_ico gs_ico_nav_next').parent['href']
            soup = _get_soup(_HOST+url)
        else:
            break
```
Last time I've checked, each row div has the class `gs_r gs_or gs_scl`, but modyfing the old class with this one gives the same empty result. So I'm thinking maybe that part of the html is now being injected after the request somehow?

**Comment by OrganicIrradiation** [comment] 2019-07-03 16:11
@jmlgh I'm not having any issues on my end with the example posted [here](https://github.com/OrganicIrradiation/scholarly/issues/41#issuecomment-499948197). Can you provide a code snippet to demonstrate your issue? That being said, I'm not using a proxy, so I can't comment on whether there may be an issue there.

**Comment by jmlgh** [comment] 2019-07-03 17:04
@OrganicIrradiation After looking at the response of the get request, it seems it was returning the recaptcha html, instead of the expected content. I’ve also been using the Tor proxies but get the same result.

**Comment by MartinBeseda** [comment] 2019-07-15 16:04
@OrganicIrradiation I'm also having the same problem getting `StopIteration`, even with your example, i.e. with this code:

```
import scholarly

proxies = {'http' : 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
scholarly.scholarly.use_proxy(**proxies)

tmp_paper_title = "Structural analysis of material flows in China based on physical and monetary input-output models"
tmp_search = scholarly.search_pubs_query(tmp_paper_title)
tmp_bib_fill = next(tmp_search).fill()

print(tmp_bib_fill.__dict__)
```

**Comment by ipeirotis** [comment] 2019-07-15 16:10
Just tried it, and this is what I get back

```
{'_filled': True,
 'bib': {'ENTRYTYPE': 'article',
         'ID': 'liang2017structural',
         'abstract': 'The physical input-output (PIO) model has different '
                     'product flow scopes from the monetary input-output (MIO) '
                     'model. Using the PIO and MIO models to analyze the '
                     'structure of material flows can identify new hotspots '
                     'for policy decisions over each other. However, PIO '
                     'models are not well-studied in existing studies on the '
                     "structure of China's material flows. This study uses "
                     'both the PIO and MIO models to analyze consumption-based '
                     'material flows of Chinese sectors and critical supply '
                     "chain paths leading to China's material flows. Results "
                     'show that …',
         'author': 'Liang, Sai and Wang, Yafei and Zhang, Tianzhu and Yang, '
                   'Zhifeng',
         'journal': 'Journal of Cleaner Production',
         'pages': '209--217',
         'publisher': 'Elsevier',
         'title': 'Structural analysis of material flows in China based on '
                  'physical and monetary input-output models',
         'url': 'https://www.sciencedirect.com/science/article/pii/S0959652617309174',
         'volume': '158',
         'year': '2017'},
 'citedby': 15,
 'id_scholarcitedby': '8920908378569697372',
 'source': 'scholar',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:XOhzwuduzXsJ:scholar.google.com/&output=citation&scisdr=CgVGh4t0GAA:AAGBfm0AAAAAXSynfZSB6QjL3E7V-gEnGz2tmyyVR64_&scisig=AAGBfm0AAAAAXSynfRQ8_L5pr72Na9f_TRIxTESQdE74&scisf=4&ct=citation&cd=0&hl=en'}
```

It seems that you need to install Tor properly.

**Comment by MartinBeseda** [comment] 2019-07-15 16:21
@ipeirotis Well, when I run `Tor`, I'm getting the following output. Is it ok? I have no previous experience with it...

```
Jul 15 18:21:01.462 [notice] Tor 0.3.3.9 (git-ca1a436fa8e53a32) running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1, Zlib 1.2.11, Liblzma 5.2.2, and Libzstd 1.3.5.
Jul 15 18:21:01.462 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 15 18:21:01.462 [notice] Read configuration file "/etc/tor/torrc".
Jul 15 18:21:01.464 [notice] Scheduler type KIST has been enabled.
Jul 15 18:21:01.464 [notice] Opening Socks listener on 127.0.0.1:9050
Jul 15 18:21:01.465 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Jul 15 18:21:01.465 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Jul 15 18:21:01.465 [err] Reading config failed--see warnings above.
```

**Comment by ipeirotis** [comment] 2019-07-15 16:26
In a Debian-based Linux system, just run:

`sudo apt-get install tor`

The tor process starts automatically and listens on port 9050.

To verify that the tor process is running, run:

`ps aux | grep '\btor\b'`

To verify the port where tor is listening, run:

`sudo netstat -l -n -p | grep tor`

**Comment by MartinBeseda** [comment] 2019-07-15 16:30
@ipeirotis Thank you! Now, the output seems ok to me...

```
$ ps aux | grep '\btor\b'
debian-+ 31557  0.2  0.2  58940 39684 ?        Ss   18:02   0:03 /usr/bin/tor --defaults-torrc /usr/share/tor/tor-service-defaults-torrc -f /etc/tor/torrc --RunAsDaemon 0
$ sudo netstat -l -n -p | grep tor
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      31557/tor           
unix  2      [ ACC ]     STREAM     LISTENING     474898   31557/tor            /var/run/tor/socks
unix  2      [ ACC ]     STREAM     LISTENING     474899   31557/tor            /var/run/tor/control
```

**Comment by MartinBeseda** [comment] 2019-07-15 16:38
@ipeirotis Also, now I'm getting another error, which is, I believe, just caused by many attempts to connect:

```
Traceback (most recent call last):
  File "test2.py", line 7, in <module>
    tmp_search = scholarly.search_pubs_query(tmp_paper_title)
  File "/home/martin/scholarly/scholarly/scholarly.py", line 320, in search_pubs_query
    soup = _get_soup(_HOST+url)
  File "/home/martin/scholarly/scholarly/scholarly.py", line 99, in _get_soup
    html = _get_page(pagerequest)
  File "/home/martin/scholarly/scholarly/scholarly.py", line 94, in _get_page
    raise Exception('Error: {0} {1}'.format(resp.status_code, resp.reason))
Exception: Error: 429 Too Many Requests
```

But, if I'm not mistaken, connecting through proxy should also deal with this, shouldn't it?

**Comment by cerkut** [comment] 2019-08-19 18:56
> @jmlgh I'm not having any issues on my end with the example posted [here](https://github.com/OrganicIrradiation/scholarly/issues/41#issuecomment-499948197). Can you provide a code snippet to demonstrate your issue? That being said, I'm not using a proxy, so I can't comment on whether there may be an issue there.

Here is my snippet, search_query works

search_query = scholarly.search_pubs_query('Awe virtual reality')
print(next(search_query))

:results:
# Out [42]: 
# output
{'_filled': False,
 'bib': {'abstract': 'The emotion of awe is characterized by the perception of '
                     'vastness and a need for accommodation, which can include '
                     'a positive and/or negative valence. While a number of '
                     'studies have successfully manipulated this emotion, the '
                     'issue of how to elicit particularly …',
         'author': 'A Chirico and DB Yaden and G Riva and A Gaggioli',
         'eprint': 'https://www.frontiersin.org/articles/10.3389/fpsyg.2016.01766',
         'title': 'The potential of virtual reality for the investigation of '
                  'awe',
         'url': 'https://www.frontiersin.org/articles/10.3389/fpsyg.2016.01766'},
 'source': 'scholar'}
:end:

but note that there is no 'url_scholarbib' field returned. Then running your example 

pub = next(scholarly.search_pubs_query('frequency-domain analysis of haptic gratings cholewiak')).fill()
print(pub)

results in an error, 

:results:


AttributeErrorTraceback (most recent call last)
<ipython-input-41-adfbb3a85b9d> in <module>
----> 1 pub = next(scholarly.search_pubs_query('frequency-domain analysis of haptic gratings cholewiak')).fill()
      2 print(pub)

/usr/local/anaconda3/envs/py373/lib/python3.7/site-packages/scholarly/scholarly.py in fill(self)
    200             self._filled = True
    201         elif self.source == 'scholar':
--> 202             bibtex = _get_page(self.url_scholarbib)
    203             self.bib.update(bibtexparser.loads(bibtex).entries[0])
    204             self._filled = True

AttributeError: 'Publication' object has no attribute 'url_scholarbib'
:end:

This is the scholarly 0.2.5 installed by pip. I'll test with latest github.

**Comment by avgurf** [comment] 2019-08-26 10:35
Hey guys, I'm also having issues, and tried using the tor proxy as @ipeirotis suggested, but can't get the `get_proxy` work. I did install it through GitHub but i might be doing somthing wrong with pip. I get this error: 
```
AttributeError: module 'scholarly' has no attribute 'use_proxy'
```
any tips?

**Comment by amyduonguk** [comment] 2020-01-05 11:04
@cerkut Hi, I got this same AttributeError. Did you figure out the problem?

**Comment by peach-byte** [comment] 2020-03-07 10:00
hello,
I have start my Tor on Macbook,
```
 brew services start tor
```
and use proxy on my proxy:
```
proxies = {'http' : 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
	scholarly.scholarly.use_proxy(**proxies)

```
But it lock on my search line of script:
```
...
search_query = scholarly.search_pubs_query("keyword")
...
```
Do I need to setup any other thing?
It seems that my script can't connect to tor!

**Comment by ipeirotis** [comment] 2020-05-12 15:43
Added examples for using proxies and Tor in the README. I am closing this issue for now.

**Closed by ipeirotis** 2020-05-12 15:43 UTC
