### ISSUE TITLE
Empty citation with get_citedby() 

### ISSUE THREAD

**Issue by liujiajun** [OrganicIrradiation/scholarly#87] opened 2020-05-14 14:22 UTC
The issue is same as #47, but I don't think the linked PR has solved the issue.

I inspected the HTML retrieved when calling get_citedby() and it shows the following:

<img width="709" alt="Screenshot 2020-05-14 at 10 19 07 PM" src="https://user-images.githubusercontent.com/2803108/81945625-eef74300-9630-11ea-8730-08062266ee4e.png">

I tried to use proxies and to no avail. Only very occasionally can I get the search results from this method. This is pretty strange since all other methods work perfectly, while this method call very often results in the "Need Javascript" prompt.

Anyone has any input on this? Thanks!

**Comment by ipeirotis** [comment] 2020-05-14 14:25
Could you please post the actual HTML here?

**Comment by liujiajun** [comment] 2020-05-14 14:30
[output-14:15:47.067311.html.zip](https://github.com/OrganicIrradiation/scholarly/files/4629017/output-14.15.47.067311.html.zip)
Here is the actual HTML

**Comment by liujiajun** [comment] 2020-05-15 08:28
It seems that the cited-by pages on Google scholar is particularly strict about robots. I could not bypass the check even with Tor/proxies. For other page it is fine

**Comment by ipeirotis** [comment] 2020-05-18 14:13
Please give us an example piece of code that causes the issue.

**Comment by ipeirotis** [comment] 2020-05-18 15:52
Duplicate of https://github.com/OrganicIrradiation/scholarly/issues/47 which is fixed.

**Closed by ipeirotis** 2020-05-18 15:52 UTC
Labels: duplicate
